--!strict
-- QuestsConfig.lua  —  ReplicatedStorage/Shared/Config/QuestsConfig.lua
-- Phase 4: 15 total quests (5 original + 10 new).

export type QuestObjectiveDef = { id:string, objectiveType:string, description:string, targetId:string, required:number }
export type QuestDef = { id:string, name:string, description:string, levelRequirement:number, prerequisiteQuests:{string}, repeatable:boolean, timeLimit:number?, objectives:{QuestObjectiveDef} }

local QuestsConfig = {}

QuestsConfig.Quests = {
	-- Original
	quest_001_first_steps     = { id="quest_001_first_steps",     name="First Steps",                levelRequirement=1,  prerequisiteQuests={},                              repeatable=false, description="Defeat the first creatures haunting the Ghostwood outskirts.",          objectives={ {id="obj_kill_slimes",          objectiveType="Kill",    description="Defeat Ghost Slimes",                   targetId="mob_ghost_slime",                  required=5}  } },
	quest_002_mistleaf_aid    = { id="quest_002_mistleaf_aid",    name="Mistleaf Aid",               levelRequirement=1,  prerequisiteQuests={},                              repeatable=false, description="Gather mistleaf for the village alchemist.",                            objectives={ {id="obj_collect_mistleaf",      objectiveType="Collect", description="Collect Mistleaf",                      targetId="item_mistleaf",                    required=10} } },
	quest_003_goblin_menace   = { id="quest_003_goblin_menace",   name="Goblin Menace",              levelRequirement=5,  prerequisiteQuests={"quest_001_first_steps"},        repeatable=false, description="Drive back the grave-goblins.",                                         objectives={ {id="obj_kill_goblins",         objectiveType="Kill",    description="Defeat Grave Goblins",                  targetId="mob_grave_goblin",                 required=10}, {id="obj_collect_goblin_charms", objectiveType="Collect", description="Collect Goblin Bone Charms", targetId="item_goblin_bone_charm", required=5} } },
	quest_004_dungeon_scout   = { id="quest_004_dungeon_scout",   name="Dungeon Scout",              levelRequirement=8,  prerequisiteQuests={"quest_003_goblin_menace"},      repeatable=false, description="Find the sealed crypt entrance.",                                       objectives={ {id="obj_explore_crypt_gate",    objectiveType="Explore", description="Discover the Sealed Crypt Gate",        targetId="zone_sealed_crypt_gate",           required=1}  } },
	quest_005_daily_hunt      = { id="quest_005_daily_hunt",      name="Daily Hunt: Restless Bones", levelRequirement=10, prerequisiteQuests={},                              repeatable=true,  description="Thin the restless undead wandering beyond the safe road.",              objectives={ {id="obj_kill_skeletons",        objectiveType="Kill",    description="Defeat Restless Skeletons",             targetId="mob_restless_skeleton",            required=15} } },
	-- Phase 4
	quest_006_wolf_pack       = { id="quest_006_wolf_pack",       name="The Phantom Pack",           levelRequirement=7,  prerequisiteQuests={"quest_001_first_steps"},        repeatable=false, description="A pack of spectral wolves has been spotted near the old mill.",          objectives={ {id="obj_kill_wolves",          objectiveType="Kill",    description="Defeat Phantom Wolves",                 targetId="mob_phantom_wolf",                 required=8},  {id="obj_collect_fang",         objectiveType="Collect", description="Collect Spectral Fangs",     targetId="item_spectral_fang",    required=3} } },
	quest_007_mist_sprites    = { id="quest_007_mist_sprites",    name="Bottled Mist",               levelRequirement=9,  prerequisiteQuests={},                              repeatable=false, description="Collect concentrated mist essence for the alchemist.",                  objectives={ {id="obj_kill_sprites",         objectiveType="Kill",    description="Defeat Mist Sprites",                   targetId="mob_mist_sprite",                  required=10}, {id="obj_collect_mist",         objectiveType="Collect", description="Collect Mist Essence",       targetId="item_mist_essence",     required=8} } },
	quest_008_revenant_rising = { id="quest_008_revenant_rising", name="Revenant Rising",            levelRequirement=10, prerequisiteQuests={"quest_004_dungeon_scout"},      repeatable=false, description="Destroy Crypt Revenants before the corruption spreads.",                 objectives={ {id="obj_kill_revenants",       objectiveType="Kill",    description="Defeat Crypt Revenants",                targetId="mob_crypt_revenant",               required=12}, {id="obj_collect_shards",       objectiveType="Collect", description="Collect Revenant Shards",    targetId="item_revenant_shard",   required=6} } },
	quest_009_elite_bounty_shaman  = { id="quest_009_elite_bounty_shaman",  name="Bounty: Goblin Shaman",    levelRequirement=6,  prerequisiteQuests={"quest_003_goblin_menace"},      repeatable=false, description="Claim the bounty on the Goblin Shaman raising the dead.",               objectives={ {id="obj_kill_shaman",          objectiveType="Kill",    description="Slay the Goblin Shaman (Elite)",        targetId="mob_elite_grave_goblin_shaman",   required=1}  } },
	quest_010_elite_bounty_knight  = { id="quest_010_elite_bounty_knight",  name="Bounty: Skeleton Knight",  levelRequirement=10, prerequisiteQuests={"quest_008_revenant_rising"},    repeatable=false, description="The garrison wants the legendary Skeleton Knight destroyed.",            objectives={ {id="obj_kill_sknight",         objectiveType="Kill",    description="Slay the Skeleton Knight (Elite)",      targetId="mob_elite_skeleton_knight",       required=1}  } },
	quest_011_mistwood_access = { id="quest_011_mistwood_access", name="Into the Depths",            levelRequirement=8,  prerequisiteQuests={"quest_002_mistleaf_aid"},       repeatable=false, description="Explore the Mistwood mine entrance and report what you find.",           objectives={ {id="obj_explore_mistwood",     objectiveType="Explore", description="Discover the Mistwood Depths Entrance", targetId="zone_mistwood_depths_gate",       required=1}  } },
	quest_012_treant_problem  = { id="quest_012_treant_problem",  name="The Treant Problem",         levelRequirement=12, prerequisiteQuests={"quest_011_mistwood_access"},    repeatable=false, description="Clear a safe path through the corrupted treants.",                      objectives={ {id="obj_kill_treants",         objectiveType="Kill",    description="Defeat Cursed Treants",                 targetId="mob_cursed_treant",                required=6},  {id="obj_collect_bark",         objectiveType="Collect", description="Collect Cursed Bark",        targetId="item_cursed_bark",      required=10} } },
	quest_013_wraith_hunters  = { id="quest_013_wraith_hunters",  name="Wraith Hunters",             levelRequirement=14, prerequisiteQuests={"quest_008_revenant_rising"},    repeatable=false, description="Collect wraith essences for the church council's bounty.",              objectives={ {id="obj_kill_wraiths",         objectiveType="Kill",    description="Defeat Wraithss",                       targetId="mob_wraith",                       required=8},  {id="obj_collect_essence",      objectiveType="Collect", description="Collect Wraith Essence",     targetId="item_wraith_essence",   required=5} } },
	quest_014_daily_mistwood  = { id="quest_014_daily_mistwood",  name="Daily: Mistwood Clearance",  levelRequirement=10, prerequisiteQuests={},                              repeatable=true,  description="The expedition camp needs the Mistwood regularly cleared.",             objectives={ {id="obj_kill_shamblers_daily", objectiveType="Kill",    description="Defeat Mistwood Shamblers",             targetId="mob_mistwood_shambler",            required=10}, {id="obj_kill_dryads_daily",    objectiveType="Kill",    description="Defeat Corrupted Dryads",    targetId="mob_mistwood_dryad",    required=5}  } },
	quest_015_guardian_slain  = { id="quest_015_guardian_slain",  name="Guardian's End",             levelRequirement=13, prerequisiteQuests={"quest_012_treant_problem"},     repeatable=false, description="Venture into the Mistwood Depths and destroy the Root Guardian.",        objectives={ {id="obj_kill_root_guardian",   objectiveType="Kill",    description="Slay the Root Guardian",                targetId="mob_root_guardian",                required=1}  } },
}

return QuestsConfig
